#!/bin/bash

chmod u+x ./Color_Palettes/color_palettes_scripte
echo "Run import color palettes script"
source ./Color_Palettes/color_palettes_scripte

echo "Import color palettes completed"

echo "Run install_font_on_mac.py"	
python ./Font/install_font_on_mac.py

echo "Import Font resources completed"
