#!/usr/bin/env bash

mkdir -p ~/Library/Colors

cp -r ./Color_Palettes/ThoughtWorks-New.clr ~/Library/Colors
cp -r ./Color_Palettes/ThoughtWorks-Old.clr ~/Library/Colors
cp -r ./Color_Palettes/Morandi.clr ~/Library/Colors
cp -r ./Color_Palettes/Popular\ 2017.clr ~/Library/Colors
cp -r ./Color_Palettes/Material.clr ~/Library/Colors
